{
 "title": "Swarm Balance",
 "description": "Graph Ethereum Wallet Balances with ease",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "name",
    "query": {
     "query": "label_values(eth_balance, name)"
    }
   },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(eth_balance, host)"
    }
   },
   {
    "name": "eth_instance",
    "label": "eth_instance",
    "query": {
     "query": "label_values(eth_balance,instance)"
    }
   },
   {
    "name": "token_instance",
    "label": "token_instance",
    "query": {
     "query": "label_values(token_balance,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "BZZ Sum - MAINNET",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(token_balance{instance=\"tokenexporter-master\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Top 5 BZZ Balances - ${token_instance}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "topk(5, token_balance{host=~\"$host\",name=~\".+\",instance=\"${token_instance}\"})",
     "legendFormat": "{{name}}-{{host}}"
    }
   ]
  },
  {
   "title": "Total Addresses Logged",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "eth_total_addresses", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "BZZ Sum - TESTNET",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(token_balance{instance=\"tokenexporter-development\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total ETH 24 Hour Change - MAINNET",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(eth_balance_total{instance=\"ethexporter-master\"} - eth_balance_total{instance=\"ethexporter-master\"} offset 24h) / eth_balance_total{instance=\"ethexporter-master\"}"
    }
   ]
  },
  {
   "title": "Total ETH 1 Hour Change",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(eth_balance_total - eth_balance_total offset 1m) / eth_balance_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "${name} ETH Week Change $eth_instance",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(eth_balance{name=~\"${name}\",instance=\"${eth_instance}\"} - eth_balance{name=~\"${name}\",instance=\"${eth_instance}\"} offset 7d) / eth_balance{name=~\"${name}\",instance=\"${eth_instance}\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "${name} ETH 1 Hour Change ${eth_instance}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "sum((eth_balance{instance=\"${eth_instance}\"} - eth_balance{instance=\"${eth_instance}\"} offset 1h) / eth_balance{instance=\"${eth_instance}\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "${name} BZZ 1 Hour Change - ${token_instance}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum((token_balance{instance=\"${token_instance}\"} - token_balance{instance=\"${token_instance}\"} offset 1h) / token_balance{instance=\"${token_instance}\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Total Load Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "eth_load_seconds", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "${name} BZZ Week Change $token_instance",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(token_balance{name=~\"${name}\",instance=\"${token_instance}\"} - token_balance{name=~\"${name}\",instance=\"${token_instance}\"} offset 7d) / token_balance{name=~\"${name}\",instance=\"${token_instance}\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "${name} ETH ${eth_instance}",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eth_balance{instance=\"${eth_instance}\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "${name} ETH 24 Hour Change $eth_instance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 16 },
   "targets": [
    {
     "expr": "(eth_balance{instance=\"${eth_instance}\",name=~\"${name}\",host=~\"${host}\"} - eth_balance{instance=\"${eth_instance}\",name=~\"${name}\",host=~\"${host}\"} offset 24h) / eth_balance{instance=\"${eth_instance}\",name=~\"${name}\",host=~\"${host}\"}",
     "legendFormat": "{{address}}-{{name}}"
    }
   ]
  },
  {
   "title": "${name} BZZ 24 Hour Change $token_instance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "(token_balance{instance=\"${token_instance}\",name=~\"${name}\",host=~\"${host}\"} - token_balance{instance=\"${token_instance}\",name=~\"${name}\",host=~\"${host}\"} offset 24h) / token_balance{instance=\"${token_instance}\",name=~\"${name}\",host=~\"${host}\"}",
     "legendFormat": "{{address}}-{{name}}"
    }
   ]
  },
  {
   "title": "${name} BZZ $token_instance",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(token_balance{instance=\"${token_instance}\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Total TOKEN 24 Hour Change - MAINNET",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (host) (delta(token_balance{instance=\"tokenexporter-master\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BZZ Balance - $token_instance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum(token_balance{instance=\"${token_instance}\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "${name} ETH Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "eth_balance_total{instance=~\".+\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}